# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-25 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190724_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_return', 'Set book as returned'),)},
        ),
    ]
