# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-25 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190725_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark', 'pizza pizza pizza'),)},
        ),
    ]
