# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-29 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190725_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('Changes_Autho', 'Changes Autho'),)},
        ),
    ]
